### ISSUE TITLE
https://blog.nianbroken.top/

### ISSUE THREAD

**Issue by NianBroken** [abbw/blog_links#10]
```yaml
name: SuiNian's Blog

link: https://blog.nianbroken.top/

avatar: https://blog.nianbroken.top/favicon.png

descr: 你歪头眯眼一笑 我便沉溺无法逃离
```
