### ISSUE TITLE
https://new.p6oy.top

### ISSUE THREAD

**Issue by ghost** [abbw/blog_links#11]
```yaml
name: P6oy的杂货铺

link: https://new.p6oy.top

avatar: https://file.p6oy.top/p6.2.webp

descr: 叼毛一个  啥都不会
```
