### ISSUE TITLE
https://www.xiaoayu.xyz/

### ISSUE THREAD

**Issue by Sunhaha520** [abbw/blog_links#7]
```yaml
name: TanSPass’S Blog
link: https://www.xiaoayu.xyz/
avatar: https://cdn.jsdelivr.net/gh/Sunhaha520/xiaoayu/touxiang.jpg
descr: 折腾无止尽。
```
