### ISSUE TITLE
https://www.chengyao.xyz

### ISSUE THREAD

**Issue by bbuugg** [abbw/blog_links#8]
```yaml
name: MaxPHP

link: https://www.chengyao.xyz

avatar: https://www.chengyao.xyz/favicon.ico

descr: 基于组件的轻量PHP框架！
```
