### ISSUE TITLE
https://blog.nianbroken.top/

### ISSUE THREAD

**Issue by NianBroken** [abbw/blog_links#9]
```yaml
name: 站点名称[SuiNian's Blog]

link: 站点链接[https://blog.nianbroken.top/]

avatar: 站点头像[https://blog.nianbroken.top/favicon.png]

descr: 站点描述[https://blog.nianbroken.top/]
```
